import { mkdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import { chromium } from 'playwright';
import type { RawDataset } from '../src/data/types';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const DATASET_PATH = join(ROOT, 'dataset/v5/lineage_v5.json');
const OUTPUT_DIR = join(ROOT, 'public/logos/graph');
const MANIFEST_PATH = join(ROOT, 'src/data/graphLogoAssets.ts');
const LOGO_SIZE = 256;

function assetNameForId(id: string): string {
  return `${id.replace(/:/g, '-').replace(/_/g, '-')}.png`;
}

function buildManifest(ids: string[]): string {
  const quotedIds = ids.map((id) => `  '${id}',`).join('\n');

  return `// Generated by scripts/renderGraphLogoAssets.ts.
// Local graph assets avoid browser canvas SVG rendering bugs in Cytoscape.

const GRAPH_LOGO_ASSET_IDS = new Set<string>([
${quotedIds}
]);

export function getGraphLogoAssetPath(id: string): string {
  return \`/logos/graph/\${id.replace(/:/g, '-').replace(/_/g, '-')}.png\`;
}

export function getGraphLogoUrl(id: string, canonicalUrl: string | null | undefined): string | null {
  if (!canonicalUrl) return null;
  return GRAPH_LOGO_ASSET_IDS.has(id) ? getGraphLogoAssetPath(id) : canonicalUrl;
}
`;
}

async function main() {
  const dataset = JSON.parse(readFileSync(DATASET_PATH, 'utf8')) as RawDataset;
  const logoNodes = dataset.languages
    .filter((node) => Boolean(node.logo_url))
    .map((node) => ({ id: node.id, name: node.name, url: node.logo_url as string }))
    .sort((a, b) => a.id.localeCompare(b.id));

  mkdirSync(OUTPUT_DIR, { recursive: true });

  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({
    viewport: { width: LOGO_SIZE, height: LOGO_SIZE },
    deviceScaleFactor: 1,
  });

  await page.setContent(`
    <!doctype html>
    <html>
      <head>
        <style>
          html, body {
            width: ${LOGO_SIZE}px;
            height: ${LOGO_SIZE}px;
            margin: 0;
            overflow: hidden;
            background: transparent;
          }
          img {
            width: ${LOGO_SIZE}px;
            height: ${LOGO_SIZE}px;
            object-fit: contain;
            display: block;
          }
        </style>
      </head>
      <body><img id="logo" alt=""></body>
    </html>
  `);

  const renderedIds: string[] = [];
  const failed: Array<{ id: string; url: string; error: string }> = [];
  const image = page.locator('#logo');

  for (const node of logoNodes) {
    try {
      await page.evaluate(
        ({ url, name }) =>
          new Promise<void>((resolve, reject) => {
            const img = document.getElementById('logo') as HTMLImageElement;
            const timeout = window.setTimeout(() => reject(new Error(`Timed out loading ${url}`)), 15000);
            img.onload = () => {
              window.clearTimeout(timeout);
              resolve();
            };
            img.onerror = () => {
              window.clearTimeout(timeout);
              reject(new Error(`Failed to load ${url}`));
            };
            img.alt = name;
            img.removeAttribute('src');
            img.src = url;
          }),
        node
      );

      await image.screenshot({
        path: join(OUTPUT_DIR, assetNameForId(node.id)),
        omitBackground: true,
      });
      renderedIds.push(node.id);
    } catch (error) {
      failed.push({
        id: node.id,
        url: node.url,
        error: error instanceof Error ? error.message : String(error),
      });
    }
  }

  await browser.close();

  writeFileSync(MANIFEST_PATH, buildManifest(renderedIds));

  console.log(`Rendered ${renderedIds.length}/${logoNodes.length} graph logo assets`);
  if (failed.length > 0) {
    console.log('Failures:');
    for (const item of failed) {
      console.log(`- ${item.id}: ${item.error}`);
    }
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
